DROP TABLE TB_LEXIA_EMPRESA CASCADE CONSTRAINTS 
;

DROP TABLE TB_LEXIA_ENDERECO CASCADE CONSTRAINTS 
;

DROP TABLE TB_LEXIA_R_EMP_END CASCADE CONSTRAINTS 
;

DROP TABLE TB_LEXIA_R_USER_END CASCADE CONSTRAINTS 
;

DROP TABLE TB_LEXIA_R_USER_SIM CASCADE CONSTRAINTS 
;

DROP TABLE TB_LEXIA_SIMULACAO CASCADE CONSTRAINTS 
;

DROP TABLE TB_LEXIA_USUARIO CASCADE CONSTRAINTS 
;