CREATE TABLE TB_LEXIA_EMPRESA 
    ( 
     ID_EMPRESA  INTEGER  NOT NULL , 
     NM_FANTASIA VARCHAR2 (100 CHAR)  NOT NULL , 
     CNPJ_EMP    VARCHAR2 (18 CHAR)  NOT NULL , 
     EMAIL_EMP   VARCHAR2 (100 CHAR)  NOT NULL , 
     TEL_EMP     VARCHAR2 (12 CHAR)  NOT NULL 
    ) 
;

ALTER TABLE TB_LEXIA_EMPRESA 
    ADD CONSTRAINT PK_EMPRESA PRIMARY KEY ( ID_EMPRESA )
    ADD CONSTRAINT CK_EMAIL_EMP CHECK (EMAIL_EMP LIKE '%_@__%.__%')
    ADD CONSTRAINT UQ_CNPJ_EMP UNIQUE (CNPJ_EMP)
    ADD CONSTRAINT UQ_EMAIL_EMP UNIQUE (EMAIL_EMP);
    

CREATE TABLE TB_LEXIA_ENDERECO 
    ( 
     ID_END     INTEGER  NOT NULL , 
     LOGRA_END  VARCHAR2 (100 CHAR)  NOT NULL , 
     NUM_END    VARCHAR2 (10 CHAR)  NOT NULL , 
     COMPLE_END VARCHAR2 (50 CHAR) , 
     BAIRRO_END VARCHAR2 (100 CHAR)  NOT NULL , 
     CID_END    VARCHAR2 (100 CHAR)  NOT NULL , 
     ESTADO_END VARCHAR2 (50 CHAR)  NOT NULL , 
     CEP_END    VARCHAR2 (9 CHAR)  NOT NULL 
    ) 
;

ALTER TABLE TB_LEXIA_ENDERECO 
    ADD CONSTRAINT PK_ENDERECO PRIMARY KEY ( ID_END ) ;

CREATE TABLE TB_LEXIA_R_EMP_END 
    ( 
     ID_END     INTEGER  NOT NULL , 
     ID_EMPRESA INTEGER  NOT NULL 
    ) 
;

ALTER TABLE TB_LEXIA_R_EMP_END 
    ADD CONSTRAINT PK_R_EMP_END PRIMARY KEY ( ID_END, ID_EMPRESA ) ;

CREATE TABLE TB_LEXIA_R_USER_END 
    ( 
     ID_END     INTEGER  NOT NULL , 
     ID_USUARIO INTEGER  NOT NULL 
    ) 
;

ALTER TABLE TB_LEXIA_R_USER_END 
    ADD CONSTRAINT PK_R_USER_END PRIMARY KEY ( ID_END, ID_USUARIO ) ;

CREATE TABLE TB_LEXIA_R_USER_SIM 
    ( 
     ID_USUARIO   INTEGER  NOT NULL , 
     ID_SIMULACAO INTEGER  NOT NULL 
    ) 
;

ALTER TABLE TB_LEXIA_R_USER_SIM 
    ADD CONSTRAINT PK_R_USER_SIM PRIMARY KEY ( ID_USUARIO, ID_SIMULACAO ) ;

CREATE TABLE TB_LEXIA_SIMULACAO 
    ( 
     ID_SIMULACAO   INTEGER  NOT NULL , 
     DT_SIMULACAO   DATE  NOT NULL , 
     TIPO_SIMULACAO VARCHAR2 (100 CHAR)  NOT NULL , 
     VL_FINAL       NUMBER  NOT NULL 
    ) 
;

ALTER TABLE TB_LEXIA_SIMULACAO 
    ADD CONSTRAINT PK_SIMULACAO PRIMARY KEY ( ID_SIMULACAO ) ;

CREATE TABLE TB_LEXIA_USUARIO 
    ( 
     ID_USUARIO                  INTEGER  NOT NULL , 
     USER_NAME                   VARCHAR2 (50 CHAR)  NOT NULL , 
     VL_SALARIO                  NUMBER  NOT NULL , 
     SENHA_USUARIO               VARCHAR2 (12)  NOT NULL , 
     TIPO_CONTRATO               VARCHAR2 (100 CHAR)  NOT NULL , 
     TB_LEXIA_EMPRESA_ID_EMPRESA INTEGER  NOT NULL 
    ) 
;

ALTER TABLE TB_LEXIA_USUARIO 
    ADD CONSTRAINT PK_USUARIO PRIMARY KEY ( ID_USUARIO )
    ADD CONSTRAINT UQ_USERNAME UNIQUE (USER_NAME)
    ADD CONSTRAINT UQ_SENHA UNIQUE (SENHA_USUARIO)
    ADD CONSTRAINT CK_SENHA_MIN_LENGTH CHECK (LENGTH(SENHA_USUARIO) >= 8)
    ;

ALTER TABLE TB_LEXIA_R_EMP_END 
    ADD CONSTRAINT FK__ENDERECO FOREIGN KEY 
    ( 
     ID_END
    ) 
    REFERENCES TB_LEXIA_ENDERECO 
    ( 
     ID_END
    ) 
;

ALTER TABLE TB_LEXIA_R_EMP_END 
    ADD CONSTRAINT FK_EMPRESA FOREIGN KEY 
    ( 
     ID_EMPRESA
    ) 
    REFERENCES TB_LEXIA_EMPRESA 
    ( 
     ID_EMPRESA
    ) 
;

ALTER TABLE TB_LEXIA_USUARIO 
    ADD CONSTRAINT FK_EMPRESAv2 FOREIGN KEY 
    ( 
     TB_LEXIA_EMPRESA_ID_EMPRESA
    ) 
    REFERENCES TB_LEXIA_EMPRESA 
    ( 
     ID_EMPRESA
    ) 
;

ALTER TABLE TB_LEXIA_R_USER_END 
    ADD CONSTRAINT FK_ENDERECO FOREIGN KEY 
    ( 
     ID_END
    ) 
    REFERENCES TB_LEXIA_ENDERECO 
    ( 
     ID_END
    ) 
;

ALTER TABLE TB_LEXIA_R_USER_SIM 
    ADD CONSTRAINT FK_SIMULACAO FOREIGN KEY 
    ( 
     ID_SIMULACAO
    ) 
    REFERENCES TB_LEXIA_SIMULACAO 
    ( 
     ID_SIMULACAO
    ) 
;

ALTER TABLE TB_LEXIA_R_USER_END 
    ADD CONSTRAINT FK_USUARIO FOREIGN KEY 
    ( 
     ID_USUARIO
    ) 
    REFERENCES TB_LEXIA_USUARIO 
    ( 
     ID_USUARIO
    ) 
;

ALTER TABLE TB_LEXIA_R_USER_SIM 
    ADD CONSTRAINT FK_USUARIOv2 FOREIGN KEY 
    ( 
     ID_USUARIO
    ) 
    REFERENCES TB_LEXIA_USUARIO 
    ( 
     ID_USUARIO
    ) 
;

