-- DROP TABLES
DROP TABLE SIMULACAO CASCADE CONSTRAINTS;
DROP TABLE USUARIO CASCADE CONSTRAINTS;
DROP TABLE EMPRESA CASCADE CONSTRAINTS;
DROP TABLE ENDERECO CASCADE CONSTRAINTS;

-- ENDERECO
CREATE TABLE ENDERECO (
    ID_ENDERECO       NUMBER PRIMARY KEY,
    LOGRADOURO        VARCHAR2(100) NOT NULL,
    NUMERO            VARCHAR2(20)  NOT NULL,
    COMPLEMENTO       VARCHAR2(50),
    BAIRRO            VARCHAR2(60)  NOT NULL,
    CIDADE            VARCHAR2(60)  NOT NULL,
    ESTADO            VARCHAR2(2)   NOT NULL,
    CEP               VARCHAR2(10)  NOT NULL
);

-- EMPRESA
CREATE TABLE EMPRESA (
    ID_EMPRESA        NUMBER PRIMARY KEY,
    NOME_FANTASIA     VARCHAR2(80)  NOT NULL,
    CNPJ              VARCHAR2(20)  NOT NULL UNIQUE,
    EMAIL             VARCHAR2(100) NOT NULL,
    TELEFONE          VARCHAR2(20) NOT NULL,
    ID_ENDERECO       NUMBER NOT NULL,
    CONSTRAINT FK_EMP_ENDERECO FOREIGN KEY (ID_ENDERECO)
        REFERENCES ENDERECO(ID_ENDERECO)
);

-- USUARIO
CREATE TABLE USUARIO (
    ID_USUARIO        NUMBER PRIMARY KEY,
    NOME              VARCHAR2(80) NOT NULL,
    EMAIL             VARCHAR2(100) NOT NULL UNIQUE,
    TELEFONE          VARCHAR2(20) NOT NULL,
    DATA_NASCIMENTO   DATE NOT NULL,
    ID_ENDERECO       NUMBER NOT NULL,
    USERNAME          VARCHAR2(40) NOT NULL UNIQUE,
    SENHA             VARCHAR2(100) NOT NULL,
    SALARIO           NUMBER(10,2) NOT NULL,
    TIPO_CONTRATO     VARCHAR2(40) NOT NULL,
    ID_EMPRESA        NUMBER NOT NULL,

    CONSTRAINT FK_USU_ENDERECO FOREIGN KEY (ID_ENDERECO)
        REFERENCES ENDERECO(ID_ENDERECO),

    CONSTRAINT FK_USU_EMPRESA FOREIGN KEY (ID_EMPRESA)
        REFERENCES EMPRESA(ID_EMPRESA)
);

-- SIMULACAO
CREATE TABLE SIMULACAO (
    ID_SIMULACAO      NUMBER PRIMARY KEY,
    ID_USUARIO        NUMBER NOT NULL,
    DATA_SIMULACAO    TIMESTAMP NOT NULL,
    TIPO_SIMULACAO    VARCHAR2(40) NOT NULL,
    VALOR_FINAL       NUMBER(10,2),
    CONSTRAINT FK_SIM_USUARIO FOREIGN KEY (ID_USUARIO)
        REFERENCES USUARIO(ID_USUARIO)
);

-- SEQUENCES (Oracle)
CREATE SEQUENCE SEQ_ENDERECO START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_EMPRESA START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_USUARIO START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_SIMULACAO START WITH 1 INCREMENT BY 1;
